# Generated by Django 4.2.5 on 2024-03-12 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='keywords',
            field=models.TextField(blank=True, null=True, verbose_name='keywords'),
        ),
    ]
