# Generated by Django 4.2.5 on 2023-12-11 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='external_product_id',
        ),
    ]
