# Generated by Django 4.2.5 on 2024-01-10 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_product_external_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('past due', 'Past Due')], default='inactive', max_length=15),
        ),
    ]
