# Generated by Django 4.2.5 on 2024-01-10 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_subscription_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='payment_gateway',
            field=models.CharField(choices=[('STRIPE', 'Stripe'), ('PAYPAL', 'Paypal')], default='STRIPE', max_length=10),
            preserve_default=False,
        ),
    ]
