# Generated by Django 4.2.5 on 2024-01-11 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_plan_payment_gateway'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='billing_frequency',
        ),
    ]
